version: '2.2'
services:
    nginx:
        hostname: nginx    
        container_name: nginx
        image: nginx
        expose:
            - "80"
        ports:
            - "8080:80"
        volumes:
            - ./app/project:/var/www/html
            - ./app/config/nginx/conf.d:/etc/nginx/conf.d:rw
            - ./app/log:/var/log/nginx
        #working_dir: /app
        #links:
        # - fpm74:fpm74
        depends_on:      
            - fpm74
        networks:
            - fronted      
        command: [nginx-debug, '-g', 'daemon off;']
    fpm74:
        hostname: fpm74
        container_name: fpm74
        build: ./fpm73-ext-docker
        expose: 
            - "9000"
        ports:
            - "9000:9000"
        volumes:
            - ./app/project:/var/www/html
              #working_dir:  /var/www/html
        depends_on:
           - mysql
           - redis
        #links:
        #   - mysql:mysql
        #  - redis:redis
        #  - mongo:mongo  
        networks:
           - fronted
           - backend     
    mysql:
       hostname: db     
       container_name: db
       image: mysql:latest
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       expose:
           - "3306"
       ports:
           - "3306:3306"
       volumes:
           - ./app/mysql:/var/lib/mysql
       environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
       networks:
          - backend     
    redis:
       hostname: redis     
       container_name: redis
       image: redis
       restart: always
       expose:
           - "6379"
       ports:
           - "6379:6379"
       volumes:
           - ./app/redis:/data
       command: redis-server --appendonly yes
       networks:
           - backend    
       logging:
           driver: json-file
           options:
               max-size: "200k" # 单个文件大小为200k
               max-file: "10" # 最多10个文件
    mongo:
       hostname: mongo     
       image: mongo
       container_name: mongo_db
       restart: always
       expose:
          - 27017
       ports:
          - "27017:27017"     
       environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
       networks:
          - backend     
    mongo-express:
       image: mongo-express
       restart: always
       ports:
          - 8081:8081
       environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root           
          ME_CONFIG_BASICAUTH_USERNAME: root
          ME_CONFIG_BASICAUTH_PASSWORD: root
      #links:
          # - mongo:mongo        
       networks:
          - backend    
    composer:
       image: composer
       container_name: composer
       command: ["composer", "install" ] #update
       volumes:
          - ./app/project:/app      
       networks:
          - fronted     
    phpmyadmin:
       image: phpmyadmin
       restart: always
       ports:
          - 8087:80
       depends_on:
          - mysql    
       environment:
          - PMA_ARBITRARY=1        
       networks:
          - backend     
networks: 
   fronted:
      driver: bridge     
   backend:        
      driver: bridge
